version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    expose:
      - "3000"
    env_file:
      - ./backend/.env
    restart: always
