version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    expose:
      - "3000"
    env_file:
      - ./backend/.env
    restart: always
